//! Request/response models for user-profile endpoints.
//!
//! Hosts the patch payload for `PATCH /me` and the request bodies of the
//! two-step email-change flow. The cross-module profile shape `UserInfo`
//! (returned by `GET /me` and the wallet login response) lives in
//! [`crate::common::models`] because both `auth` and `users` produce it.

use email_address::EmailAddress;
use secrecy::{ExposeSecret, SecretString};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::{
    common::{self, ApiError, ApiResult, UserRole},
    services::users::db::ProfilePatch,
};

const MAX_NAME_LEN: usize = 100;
const MAX_PHONE_LEN: usize = 20;
const MAX_BIO_LEN: usize = 1024;

/// RFC 5321 hard limit on the full email address length.
///
/// Enforced explicitly because `EmailAddress::is_valid` accepts addresses
/// past this size when individual labels are shorter than their RFC limits.
const MAX_EMAIL_LEN: usize = 254;
/// Length of the base64url-no-pad encoding of 32 random bytes.
///
/// Kept as an exact match (not a range) because the token is generated by
/// our own handler with a fixed-size RNG buffer; any deviation is either a
/// truncation attack or a copy-paste error and must 400 before any Redis
/// round-trip happens.
const EMAIL_CHANGE_TOKEN_LEN: usize = 43;

/// Magic string a client must send in the body to confirm self-deletion.
///
/// Matched verbatim by [`DeleteAccountRequest::into_validated`]. The value
/// is part of the public contract, so changing it later requires a docs
/// pass on `docs/api/users.md` and a coordinated client update -
/// otherwise every existing client would silently 400 on `DELETE /me`.
pub const ACCOUNT_DELETE_CONFIRMATION: &str = "delete-my-account";

/// Patch payload for `PATCH /api/v1/users/me`.
///
/// Each field is optional; a missing field leaves the underlying column
/// unchanged (the SQL update uses `COALESCE($n, col)`). Only mutable profile
/// fields are exposed:
///
/// - `email` is owned by a dedicated email-change flow (separate endpoint)
///   where a verification round-trip guards uniqueness.
/// - `role`, `status`, and `verification_level` are admin-controlled and not
///   self-editable.
///
/// Unknown JSON keys are silently dropped by serde, so a client that posts
/// `{"role": "admin"}` together with valid fields is treated as if `role`
/// were absent rather than 400-rejected.
#[derive(Debug, Deserialize, ToSchema)]
pub struct UpdateProfileRequest {
    /// First name (1-100 chars after trim, NOT NULL in schema).
    pub first_name: Option<String>,
    /// Last name (1-100 chars after trim, NOT NULL in schema).
    pub last_name: Option<String>,
    /// Phone number (1-20 chars after trim).
    pub phone: Option<String>,
    /// Free-form bio (up to 1024 chars after trim).
    pub bio: Option<String>,
}

impl UpdateProfileRequest {
    /// Trims whitespace, validates lengths, and produces a `ProfilePatch`
    /// ready for the db layer.
    ///
    /// Validation lives at the request layer (not in `db.rs`) so bad input
    /// is rejected before any SQL is issued and the boundary stays at the
    /// HTTP edge.
    ///
    /// # Errors
    ///
    /// Returns [`ApiError::BadRequest`] when:
    /// - a NOT-NULL column (`first_name`, `last_name`) or `phone` arrives as
    ///   an all-whitespace string (the user cannot wipe a required column or
    ///   set a "verified-empty" phone number);
    /// - any field exceeds its length cap.
    #[inline]
    pub fn into_patch(self) -> ApiResult<ProfilePatch> {
        Ok(ProfilePatch {
            first_name: trim_required("first_name", self.first_name, MAX_NAME_LEN)?,
            last_name: trim_required("last_name", self.last_name, MAX_NAME_LEN)?,
            phone: trim_required("phone", self.phone, MAX_PHONE_LEN)?,
            bio: trim_optional("bio", self.bio, MAX_BIO_LEN)?,
        })
    }
}

/// Normalizes input for a column where the stored value must not become
/// empty (`first_name`, `last_name`, `phone` after trim).
///
/// `None` (field omitted) -> `None`, leaves the column unchanged.
/// `Some("")` or whitespace-only -> `BadRequest`, blocks accidental wipes.
fn trim_required(field: &str, value: Option<String>, max_len: usize) -> ApiResult<Option<String>> {
    let Some(raw) = value else {
        return Ok(None);
    };
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return Err(ApiError::BadRequest(format!("{field} cannot be empty")));
    }
    if trimmed.chars().count() > max_len {
        return Err(ApiError::BadRequest(format!(
            "{field} must be at most {max_len} characters"
        )));
    }
    Ok(Some(trimmed.to_owned()))
}

/// Normalizes input for a column where empty input is acceptable (`bio`).
///
/// Trimmed-empty is treated as "leave unchanged" rather than "clear column".
/// The current SQL uses `COALESCE($n, col)` and cannot distinguish "skip
/// field" from "set NULL"; clearing requires a follow-up endpoint or an
/// explicit sentinel and is not in scope for this patch.
fn trim_optional(field: &str, value: Option<String>, max_len: usize) -> ApiResult<Option<String>> {
    let Some(raw) = value else {
        return Ok(None);
    };
    let trimmed = raw.trim();
    if trimmed.chars().count() > max_len {
        return Err(ApiError::BadRequest(format!(
            "{field} must be at most {max_len} characters"
        )));
    }
    if trimmed.is_empty() {
        return Ok(None);
    }
    Ok(Some(trimmed.to_owned()))
}

/// Request body for `POST /api/v1/users/me/email`.
///
/// Initiates an email change: a confirmation token is emailed to the
/// `new_email`, and the column is rewritten only after the user clicks the
/// link and posts the token to `/me/email/confirm`. The two-step flow
/// guarantees the new address is reachable before any DB write.
#[derive(Debug, Deserialize, ToSchema)]
pub struct EmailChangeRequest {
    /// New email address (RFC 5322 valid after trim+lowercase, capped at
    /// 254 chars per RFC 5321).
    pub new_email: String,
}

impl EmailChangeRequest {
    /// Trims, lowercases, and RFC-validates the candidate email.
    ///
    /// Format-validation is delegated to [`EmailAddress::is_valid`] so we
    /// do not maintain a hand-rolled regex - the crate handles IDN,
    /// quoted local-parts, and IP-literal domains correctly.
    /// Reachability is still proved by the confirmation round-trip; this
    /// check just rejects obviously-malformed input before the Redis
    /// round-trip and email send.
    ///
    /// # Errors
    ///
    /// Returns [`ApiError::BadRequest`] when the input exceeds
    /// [`MAX_EMAIL_LEN`] or fails the RFC 5322 syntactic check.
    #[inline]
    pub fn into_validated(self) -> ApiResult<String> {
        let normalized = self.new_email.trim().to_ascii_lowercase();
        if normalized.len() > MAX_EMAIL_LEN {
            return Err(ApiError::BadRequest(format!(
                "new_email must be at most {MAX_EMAIL_LEN} characters"
            )));
        }
        if !EmailAddress::is_valid(&normalized) {
            return Err(ApiError::BadRequest(
                "new_email is not a valid email address".to_owned(),
            ));
        }
        Ok(normalized)
    }
}

/// Request body for `POST /api/v1/users/me/email/confirm`.
///
/// Carries the opaque token the client received via email and forwards
/// from the deep-link landing page. The handler hashes it, looks up the
/// pending change in Redis, and applies the column rewrite.
#[derive(Debug, Deserialize, ToSchema)]
pub struct EmailChangeConfirmRequest {
    /// Opaque confirmation token (exactly 43 base64url-no-pad chars,
    /// `[A-Za-z0-9_-]`).
    pub token: String,
}

/// Request body for `PATCH /api/v1/users/me/role`.
///
/// Carries the role the authenticated user wants to switch to. Whitelist
/// enforcement (`tenant`, `landlord`, `agent`) lives in
/// [`UpdateRoleRequest::into_validated`] rather than at the serde layer:
/// `UserRole` already maps any unknown string to its `Unknown` fallback
/// variant, so the JSON layer is intentionally lenient and the `into_validated`
/// gate produces a single, stable 400 wording for every non-whitelisted input
/// (including `admin`, `property_manager`, and the serde fallback).
#[derive(Debug, Deserialize, ToSchema)]
pub struct UpdateRoleRequest {
    /// Desired role. Only the self-registerable subset is accepted; see
    /// [`UpdateRoleRequest::into_validated`] for the rejection rationale.
    pub role: UserRole,
}

impl UpdateRoleRequest {
    /// Validates the requested role against the self-registerable whitelist.
    ///
    /// Reuses [`UserRole::is_self_registerable`] (the same gate the wallet
    /// login path applies to its `LoginRequest.role` field) so the two
    /// surfaces cannot drift: a future change to the whitelist propagates
    /// automatically. Privileged roles (`admin`, `property_manager`) and
    /// the `Unknown` fallback (any unrecognized string) are rejected here
    /// rather than at the DB CHECK constraint - the constraint's failure
    /// mode is a generic 500 with an opaque postgres error, while this
    /// gate produces a clean 400 with a stable wording naming the
    /// allowed values.
    ///
    /// # Errors
    ///
    /// Returns [`ApiError::BadRequest`] when the requested role is not on
    /// the user-self-registerable whitelist.
    #[inline]
    pub fn into_validated(self) -> ApiResult<UserRole> {
        if !self.role.is_self_registerable() {
            return Err(ApiError::BadRequest(
                "role must be one of: tenant, landlord, agent".to_owned(),
            ));
        }
        Ok(self.role)
    }
}

/// Response body for `POST /api/v1/users/me/avatar`.
///
/// Carries only the URL the storage backend assigned to the freshly-uploaded
/// blob. The full profile is intentionally NOT echoed: the user already has
/// it from `GET /me`, and rebuilding the join (`active_leases_count`,
/// `verification_level`) costs a second SQL trip that the avatar UI does not
/// need to render. Clients that care about the joined shape can re-fetch
/// `GET /me` after the upload completes.
#[derive(Debug, Serialize, ToSchema)]
pub struct AvatarUploadResponse {
    /// Public URL of the stored avatar. With `StubMediaStorage` this is a
    /// `data:image/svg+xml;base64,...` placeholder; with the production
    /// `S3MediaStorage` it is a CDN-shaped URL pointing at the bucket.
    pub avatar_url: String,
}

impl EmailChangeConfirmRequest {
    /// Validates the token shape before any Redis lookup.
    ///
    /// Strict shape-checking up front avoids accidentally hashing
    /// arbitrary client input - `Sha256::digest` is constant-time on the
    /// presented bytes regardless of length, but rejecting malformed
    /// tokens early gives a clean 400 (vs. a generic 401 after the
    /// inevitable miss) and protects against log-spam from random
    /// fuzzing.
    ///
    /// # Errors
    ///
    /// Returns [`ApiError::BadRequest`] when the token has the wrong
    /// length or contains non-base64url characters.
    #[inline]
    pub fn into_validated(self) -> ApiResult<String> {
        let trimmed = self.token.trim();
        if trimmed.len() != EMAIL_CHANGE_TOKEN_LEN {
            return Err(ApiError::BadRequest("Invalid token length".to_owned()));
        }
        if !trimmed
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        {
            return Err(ApiError::BadRequest("Invalid token format".to_owned()));
        }
        Ok(trimmed.to_owned())
    }
}

/// Request body for `DELETE /api/v1/users/me`.
///
/// Carries an explicit confirmation string so a stray client (e.g. an
/// over-eager retry that posts an empty body) cannot accidentally soft-delete
/// the user. The string is matched verbatim against
/// [`ACCOUNT_DELETE_CONFIRMATION`]; any other value 400's. The flow is "magic
/// constant in the body" rather than "extra header" because the body is what
/// the operator sees in their request log when investigating a deletion - the
/// confirmation string travels with the row, not with transport-level metadata
/// that gets stripped on the way to the audit trail.
#[derive(Debug, Deserialize, ToSchema)]
pub struct DeleteAccountRequest {
    /// Must equal [`ACCOUNT_DELETE_CONFIRMATION`] verbatim. Trimming is NOT
    /// performed: a client that sends `" delete-my-account "` almost certainly
    /// has a UI bug, and we want them to surface the 400 immediately rather
    /// than silently accepting whitespace as equivalent.
    ///
    /// `#[serde(default)]` keeps the failure mode uniform: a missing field
    /// deserializes to `""` which fails the equality check below and yields
    /// the same 400 with the same wording as a wrong value. Without
    /// `default`, axum 0.8 surfaces the missing-field path as 422
    /// (`JsonDataError`), splitting the contract into two status codes for
    /// what is, from the client's perspective, the same "you forgot the
    /// confirmation string" mistake.
    #[serde(default)]
    pub confirm: String,
}

impl DeleteAccountRequest {
    /// Validates the confirmation string against
    /// [`ACCOUNT_DELETE_CONFIRMATION`].
    ///
    /// Returns `()` because the only useful information in the request is
    /// whether the gate passes - there is no normalized value to hand back to
    /// the handler. The handler reads `user_id` from the JWT, not from the
    /// request body, so no client-supplied identity can sneak through this
    /// gate.
    ///
    /// # Errors
    ///
    /// Returns [`ApiError::BadRequest`] when `confirm` does not match the
    /// expected magic string.
    #[inline]
    pub fn into_validated(self) -> ApiResult<()> {
        if self.confirm != ACCOUNT_DELETE_CONFIRMATION {
            return Err(ApiError::BadRequest(format!(
                "confirm must equal '{ACCOUNT_DELETE_CONFIRMATION}'"
            )));
        }
        Ok(())
    }
}

/// Request body for `POST /api/v1/users/me/password`.
///
/// One endpoint serves two cases, distinguished by whether the account already
/// has a `password_hash`:
///
/// - **change** (a password account): `current_password` is required and
///   verified before the rewrite.
/// - **set** (a wallet-only / OAuth-only account setting its first password):
///   `current_password` is absent; the handler requires a freshly
///   authenticated session instead.
///
/// Both passwords are `SecretString` so they never land in `Debug` output or
/// logs. The `value_type` overrides keep the `OpenAPI` schema as plain strings
/// - `SecretString` has no `ToSchema` of its own.
#[derive(Debug, Deserialize, ToSchema)]
pub struct ChangePasswordRequest {
    /// Current password. Required to change an existing password; omitted (or
    /// `null`) when setting the first password on a wallet-only account.
    #[schema(value_type = Option<String>)]
    pub current_password: Option<SecretString>,
    /// New password. Must satisfy the same policy as registration (length plus
    /// a digit and mixed case).
    #[schema(value_type = String)]
    pub new_password: SecretString,
}

/// A [`ChangePasswordRequest`] whose `new_password` has passed the policy.
///
/// `current_password` is carried through unchanged - whether it is required at
/// all depends on the change-vs-set branch the handler resolves from the
/// stored hash, which the request layer cannot see. `new_password` stays
/// plaintext here; hashing is the handler's CPU-heavy side effect.
#[derive(Debug)]
pub struct ValidatedPasswordChange {
    /// Presented current password, if any. `None` is only valid on the set path.
    pub current_password: Option<SecretString>,
    /// Policy-checked but not-yet-hashed new password.
    pub new_password: SecretString,
}

impl ChangePasswordRequest {
    /// Validates `new_password` against the account-password policy.
    ///
    /// Runs at the HTTP boundary so a weak password is rejected before any
    /// hash verification or SQL happens. `current_password` is intentionally
    /// NOT checked here - its necessity is a function of the account's stored
    /// hash, which only the handler knows.
    ///
    /// # Errors
    ///
    /// Returns [`ApiError::BadRequest`] when `new_password` fails the policy.
    #[inline]
    pub fn into_validated(self) -> ApiResult<ValidatedPasswordChange> {
        common::validate_password_policy(self.new_password.expose_secret())?;
        Ok(ValidatedPasswordChange {
            current_password: self.current_password,
            new_password: self.new_password,
        })
    }
}
