//! Request/response models for user-profile endpoints.
//!
//! Hosts the patch payload for `PATCH /me` and the request bodies of the
//! two-step email-change flow. The cross-module profile shape `UserInfo`
//! (returned by `GET /me` and the wallet login response) lives in
//! [`crate::common::models`] because both `auth` and `users` produce it.

use email_address::EmailAddress;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::{
    common::{ApiError, ApiResult},
    services::users::db::ProfilePatch,
};

const MAX_NAME_LEN: usize = 100;
const MAX_PHONE_LEN: usize = 20;
const MAX_BIO_LEN: usize = 1024;
const MAX_AVATAR_URL_LEN: usize = 2048;

/// RFC 5321 hard limit on the full email address length.
///
/// Enforced explicitly because `EmailAddress::is_valid` accepts addresses
/// past this size when individual labels are shorter than their RFC limits.
const MAX_EMAIL_LEN: usize = 254;
/// Length of the base64url-no-pad encoding of 32 random bytes.
///
/// Kept as an exact match (not a range) because the token is generated by
/// our own handler with a fixed-size RNG buffer; any deviation is either a
/// truncation attack or a copy-paste error and must 400 before any Redis
/// round-trip happens.
const EMAIL_CHANGE_TOKEN_LEN: usize = 43;

/// Patch payload for `PATCH /api/v1/users/me`.
///
/// Each field is optional; a missing field leaves the underlying column
/// unchanged (the SQL update uses `COALESCE($n, col)`). Only mutable profile
/// fields are exposed:
///
/// - `email` is owned by a dedicated email-change flow (separate endpoint)
///   where a verification round-trip guards uniqueness.
/// - `role`, `status`, and `verification_level` are admin-controlled and not
///   self-editable.
///
/// Unknown JSON keys are silently dropped by serde, so a client that posts
/// `{"role": "admin"}` together with valid fields is treated as if `role`
/// were absent rather than 400-rejected.
#[derive(Debug, Deserialize, ToSchema)]
pub struct UpdateProfileRequest {
    /// First name (1-100 chars after trim, NOT NULL in schema).
    pub first_name: Option<String>,
    /// Last name (1-100 chars after trim, NOT NULL in schema).
    pub last_name: Option<String>,
    /// Phone number (1-20 chars after trim).
    pub phone: Option<String>,
    /// Free-form bio (up to 1024 chars after trim).
    pub bio: Option<String>,
    /// Avatar URL (up to 2048 chars after trim).
    pub avatar_url: Option<String>,
}

impl UpdateProfileRequest {
    /// Trims whitespace, validates lengths, and produces a `ProfilePatch`
    /// ready for the db layer.
    ///
    /// Validation lives at the request layer (not in `db.rs`) so bad input
    /// is rejected before any SQL is issued and the boundary stays at the
    /// HTTP edge.
    ///
    /// # Errors
    ///
    /// Returns [`ApiError::BadRequest`] when:
    /// - a NOT-NULL column (`first_name`, `last_name`) or `phone` arrives as
    ///   an all-whitespace string (the user cannot wipe a required column or
    ///   set a "verified-empty" phone number);
    /// - any field exceeds its length cap.
    #[inline]
    pub fn into_patch(self) -> ApiResult<ProfilePatch> {
        Ok(ProfilePatch {
            first_name: trim_required("first_name", self.first_name, MAX_NAME_LEN)?,
            last_name: trim_required("last_name", self.last_name, MAX_NAME_LEN)?,
            phone: trim_required("phone", self.phone, MAX_PHONE_LEN)?,
            bio: trim_optional("bio", self.bio, MAX_BIO_LEN)?,
            avatar_url: trim_optional("avatar_url", self.avatar_url, MAX_AVATAR_URL_LEN)?,
        })
    }
}

/// Normalizes input for a column where the stored value must not become
/// empty (`first_name`, `last_name`, `phone` after trim).
///
/// `None` (field omitted) -> `None`, leaves the column unchanged.
/// `Some("")` or whitespace-only -> `BadRequest`, blocks accidental wipes.
fn trim_required(field: &str, value: Option<String>, max_len: usize) -> ApiResult<Option<String>> {
    let Some(raw) = value else {
        return Ok(None);
    };
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return Err(ApiError::BadRequest(format!("{field} cannot be empty")));
    }
    if trimmed.chars().count() > max_len {
        return Err(ApiError::BadRequest(format!(
            "{field} must be at most {max_len} characters"
        )));
    }
    Ok(Some(trimmed.to_owned()))
}

/// Normalizes input for a column where empty input is acceptable
/// (`bio`, `avatar_url`).
///
/// Trimmed-empty is treated as "leave unchanged" rather than "clear column".
/// The current SQL uses `COALESCE($n, col)` and cannot distinguish "skip
/// field" from "set NULL"; clearing requires a follow-up endpoint or an
/// explicit sentinel and is not in scope for this patch.
fn trim_optional(field: &str, value: Option<String>, max_len: usize) -> ApiResult<Option<String>> {
    let Some(raw) = value else {
        return Ok(None);
    };
    let trimmed = raw.trim();
    if trimmed.chars().count() > max_len {
        return Err(ApiError::BadRequest(format!(
            "{field} must be at most {max_len} characters"
        )));
    }
    if trimmed.is_empty() {
        return Ok(None);
    }
    Ok(Some(trimmed.to_owned()))
}

/// Request body for `POST /api/v1/users/me/email`.
///
/// Initiates an email change: a confirmation token is emailed to the
/// `new_email`, and the column is rewritten only after the user clicks the
/// link and posts the token to `/me/email/confirm`. The two-step flow
/// guarantees the new address is reachable before any DB write.
#[derive(Debug, Deserialize, ToSchema)]
pub struct EmailChangeRequest {
    /// New email address (RFC 5322 valid after trim+lowercase, capped at
    /// 254 chars per RFC 5321).
    pub new_email: String,
}

impl EmailChangeRequest {
    /// Trims, lowercases, and RFC-validates the candidate email.
    ///
    /// Format-validation is delegated to [`EmailAddress::is_valid`] so we
    /// do not maintain a hand-rolled regex - the crate handles IDN,
    /// quoted local-parts, and IP-literal domains correctly.
    /// Reachability is still proved by the confirmation round-trip; this
    /// check just rejects obviously-malformed input before the Redis
    /// round-trip and email send.
    ///
    /// # Errors
    ///
    /// Returns [`ApiError::BadRequest`] when the input exceeds
    /// [`MAX_EMAIL_LEN`] or fails the RFC 5322 syntactic check.
    #[inline]
    pub fn into_validated(self) -> ApiResult<String> {
        let normalized = self.new_email.trim().to_ascii_lowercase();
        if normalized.len() > MAX_EMAIL_LEN {
            return Err(ApiError::BadRequest(format!(
                "new_email must be at most {MAX_EMAIL_LEN} characters"
            )));
        }
        if !EmailAddress::is_valid(&normalized) {
            return Err(ApiError::BadRequest(
                "new_email is not a valid email address".to_owned(),
            ));
        }
        Ok(normalized)
    }
}

/// Request body for `POST /api/v1/users/me/email/confirm`.
///
/// Carries the opaque token the client received via email and forwards
/// from the deep-link landing page. The handler hashes it, looks up the
/// pending change in Redis, and applies the column rewrite.
#[derive(Debug, Deserialize, ToSchema)]
pub struct EmailChangeConfirmRequest {
    /// Opaque confirmation token (exactly 43 base64url-no-pad chars,
    /// `[A-Za-z0-9_-]`).
    pub token: String,
}

/// Response body for `POST /api/v1/users/me/avatar`.
///
/// Carries only the URL the storage backend assigned to the freshly-uploaded
/// blob. The full profile is intentionally NOT echoed: the user already has
/// it from `GET /me`, and rebuilding the join (`active_leases_count`,
/// `verification_level`) costs a second SQL trip that the avatar UI does not
/// need to render. Clients that care about the joined shape can re-fetch
/// `GET /me` after the upload completes.
#[derive(Debug, Serialize, ToSchema)]
pub struct AvatarUploadResponse {
    /// Public URL of the stored avatar. With `StubMediaStorage` this is a
    /// `data:image/svg+xml;base64,...` placeholder; with the production
    /// `S3MediaStorage` it is a CDN-shaped URL pointing at the bucket.
    pub avatar_url: String,
}

impl EmailChangeConfirmRequest {
    /// Validates the token shape before any Redis lookup.
    ///
    /// Strict shape-checking up front avoids accidentally hashing
    /// arbitrary client input - `Sha256::digest` is constant-time on the
    /// presented bytes regardless of length, but rejecting malformed
    /// tokens early gives a clean 400 (vs. a generic 401 after the
    /// inevitable miss) and protects against log-spam from random
    /// fuzzing.
    ///
    /// # Errors
    ///
    /// Returns [`ApiError::BadRequest`] when the token has the wrong
    /// length or contains non-base64url characters.
    #[inline]
    pub fn into_validated(self) -> ApiResult<String> {
        let trimmed = self.token.trim();
        if trimmed.len() != EMAIL_CHANGE_TOKEN_LEN {
            return Err(ApiError::BadRequest("Invalid token length".to_owned()));
        }
        if !trimmed
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        {
            return Err(ApiError::BadRequest("Invalid token format".to_owned()));
        }
        Ok(trimmed.to_owned())
    }
}
