import { Property, BuyerProfile, Wishlist, Tour, Offer, Message, MarketInsight, Notification, BuyerActivity } from '../types/buyer';

export const mockBuyerProfile: BuyerProfile = {
  id: 'buyer-001',
  name: 'Sarah Johnson',
  email: 'sarah.johnson@email.com',
  phone: '(555) 123-4567',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  preferences: {
    minPrice: 300000,
    maxPrice: 600000,
    bedrooms: [3, 4],
    bathrooms: [2, 3],
    propertyTypes: ['house', 'townhouse'],
    locations: ['San Francisco', 'Oakland', 'Berkeley'],
    mustHaveFeatures: ['garage', 'backyard', 'updated kitchen'],
    commuteAddress: '123 Market St, San Francisco, CA',
    maxCommuteTime: 45,
  },
  savedSearches: [
    {
      id: 'search-1',
      name: 'Family Homes in SF',
      filters: {
        minPrice: 400000,
        maxPrice: 600000,
        bedrooms: [3, 4],
        cities: ['San Francisco'],
        propertyTypes: ['house'],
      },
      alertsEnabled: true,
      createdAt: '2025-01-15',
      newListingsCount: 3,
    },
    {
      id: 'search-2',
      name: 'East Bay Townhouses',
      filters: {
        minPrice: 300000,
        maxPrice: 500000,
        cities: ['Oakland', 'Berkeley'],
        propertyTypes: ['townhouse'],
      },
      alertsEnabled: true,
      createdAt: '2025-01-20',
      newListingsCount: 5,
    },
  ],
  prequalificationStatus: 'approved',
  prequalificationAmount: 550000,
  lenderInfo: {
    name: 'Premier Home Loans',
    contact: '(555) 987-6543',
    loanOfficer: 'Michael Chen',
  },
};

export const mockProperties: Property[] = [
  {
    id: 'prop-001',
    title: 'Beautiful Victorian Home with Modern Updates',
    address: '456 Oak Street',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    price: 525000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1850,
    propertyType: 'house',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    description: 'Charming Victorian home featuring original hardwood floors, high ceilings, and a completely renovated kitchen with stainless steel appliances. Spacious backyard perfect for entertaining.',
    yearBuilt: 1920,
    lotSize: 3500,
    features: ['hardwood floors', 'updated kitchen', 'backyard', 'garage', 'fireplace'],
    agentId: 'agent-001',
    agentName: 'Jennifer Martinez',
    agentPhone: '(555) 234-5678',
    agentEmail: 'jennifer.martinez@realty.com',
    listingDate: '2025-01-10',
    daysOnMarket: 23,
    views: 342,
    inquiries: 18,
    tourRequests: 12,
    latitude: 37.7749,
    longitude: -122.4194,
    schoolRating: 8,
    walkScore: 92,
    transitScore: 88,
    crimeRate: 'low',
    nearbyAmenities: ['Grocery Store', 'Park', 'School', 'Restaurant', 'Coffee Shop'],
  },
  {
    id: 'prop-002',
    title: 'Modern Townhouse in Prime Location',
    address: '789 Elm Avenue',
    city: 'Oakland',
    state: 'CA',
    zipCode: '94612',
    price: 475000,
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 1650,
    propertyType: 'townhouse',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    ],
    description: 'Contemporary townhouse with open floor plan, gourmet kitchen, and rooftop deck with stunning city views. Walking distance to BART station.',
    yearBuilt: 2018,
    lotSize: 1200,
    features: ['open floor plan', 'rooftop deck', 'stainless appliances', 'garage', 'walk-in closet'],
    agentId: 'agent-002',
    agentName: 'David Thompson',
    agentPhone: '(555) 345-6789',
    agentEmail: 'david.thompson@realty.com',
    listingDate: '2025-01-25',
    daysOnMarket: 8,
    views: 156,
    inquiries: 9,
    tourRequests: 7,
    latitude: 37.8044,
    longitude: -122.2712,
    schoolRating: 7,
    walkScore: 85,
    transitScore: 95,
    crimeRate: 'medium',
    nearbyAmenities: ['BART Station', 'Shopping Center', 'Gym', 'Restaurant'],
  },
  {
    id: 'prop-003',
    title: 'Spacious Family Home with Pool',
    address: '321 Pine Drive',
    city: 'Berkeley',
    state: 'CA',
    zipCode: '94704',
    price: 595000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2400,
    propertyType: 'house',
    status: 'active',
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
      '/images/FamilyHome.jpg',
    ],
    description: 'Stunning single-family home with pool, large backyard, and mountain views. Perfect for families seeking space and comfort.',
    yearBuilt: 2005,
    lotSize: 6000,
    features: ['pool', 'mountain view', 'large backyard', '2-car garage', 'master suite'],
    agentId: 'agent-003',
    agentName: 'Lisa Anderson',
    agentPhone: '(555) 456-7890',
    agentEmail: 'lisa.anderson@realty.com',
    listingDate: '2025-01-05',
    daysOnMarket: 28,
    views: 428,
    inquiries: 24,
    tourRequests: 15,
    latitude: 37.8715,
    longitude: -122.2730,
    schoolRating: 9,
    walkScore: 78,
    transitScore: 72,
    crimeRate: 'low',
    nearbyAmenities: ['UC Berkeley', 'Park', 'Library', 'Shopping'],
  },
];

export const mockWishlists: Wishlist[] = [
  {
    id: 'wishlist-001',
    name: 'Top Favorites',
    properties: [mockProperties[0], mockProperties[2]],
    createdAt: '2025-01-15',
    updatedAt: '2025-02-01',
    notes: 'Properties I want to tour this weekend',
  },
  {
    id: 'wishlist-002',
    name: 'Budget Options',
    properties: [mockProperties[1]],
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
];

export const mockTours: Tour[] = [
  {
    id: 'tour-001',
    propertyId: 'prop-001',
    property: mockProperties[0],
    scheduledDate: '2025-02-05',
    scheduledTime: '2:00 PM',
    type: 'in-person',
    status: 'scheduled',
    agentId: 'agent-001',
    agentName: 'Jennifer Martinez',
    notes: 'Interested in seeing the backyard and kitchen renovations',
  },
  {
    id: 'tour-002',
    propertyId: 'prop-002',
    property: mockProperties[1],
    scheduledDate: '2025-02-06',
    scheduledTime: '10:00 AM',
    type: 'virtual',
    status: 'scheduled',
    agentId: 'agent-002',
    agentName: 'David Thompson',
  },
  {
    id: 'tour-003',
    propertyId: 'prop-003',
    property: mockProperties[2],
    scheduledDate: '2025-01-28',
    scheduledTime: '3:00 PM',
    type: 'in-person',
    status: 'completed',
    agentId: 'agent-003',
    agentName: 'Lisa Anderson',
    feedback: 'Beautiful property, loved the pool and backyard space',
    rating: 5,
  },
];

export const mockOffers: Offer[] = [
  {
    id: 'offer-001',
    propertyId: 'prop-003',
    property: mockProperties[2],
    offerAmount: 580000,
    earnestMoney: 10000,
    contingencies: ['Inspection', 'Financing', 'Appraisal'],
    closingDate: '2025-03-15',
    status: 'submitted',
    submittedAt: '2025-01-30',
    documents: [
      {
        id: 'doc-001',
        name: 'Purchase Agreement',
        type: 'pdf',
        url: '/documents/purchase-agreement.pdf',
        uploadedAt: '2025-01-30',
        uploadedBy: 'Sarah Johnson',
        size: 245000,
        status: 'pending',
      },
      {
        id: 'doc-002',
        name: 'Pre-qualification Letter',
        type: 'pdf',
        url: '/documents/prequalification.pdf',
        uploadedAt: '2025-01-30',
        uploadedBy: 'Sarah Johnson',
        size: 156000,
        status: 'approved',
      },
    ],
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    senderId: 'agent-001',
    senderName: 'Jennifer Martinez',
    senderRole: 'agent',
    recipientId: 'buyer-001',
    recipientName: 'Sarah Johnson',
    subject: 'Tour Confirmation - 456 Oak Street',
    content: 'Hi Sarah, I wanted to confirm your tour for tomorrow at 2:00 PM. Looking forward to showing you this beautiful Victorian home!',
    timestamp: '2025-02-04T10:30:00Z',
    read: false,
    propertyId: 'prop-001',
  },
  {
    id: 'msg-002',
    senderId: 'lender-001',
    senderName: 'Michael Chen',
    senderRole: 'lender',
    recipientId: 'buyer-001',
    recipientName: 'Sarah Johnson',
    subject: 'Pre-qualification Update',
    content: 'Good news! Your pre-qualification has been approved for up to $550,000. Please let me know if you have any questions.',
    timestamp: '2025-02-03T14:15:00Z',
    read: true,
  },
  {
    id: 'msg-003',
    senderId: 'agent-003',
    senderName: 'Lisa Anderson',
    senderRole: 'agent',
    recipientId: 'buyer-001',
    recipientName: 'Sarah Johnson',
    subject: 'Offer Response - 321 Pine Drive',
    content: 'The seller has reviewed your offer and would like to discuss. Can we schedule a call this afternoon?',
    timestamp: '2025-02-01T09:00:00Z',
    read: true,
    propertyId: 'prop-003',
  },
];

export const mockMarketInsights: MarketInsight[] = [
  {
    id: 'market-001',
    location: 'San Francisco, CA',
    averagePrice: 1250000,
    medianPrice: 1100000,
    priceChange: 45000,
    priceChangePercent: 3.8,
    daysOnMarket: 32,
    inventoryLevel: 'low',
    marketTrend: 'sellers',
    recentSales: 156,
    newListings: 89,
    period: 'Last 30 Days',
  },
  {
    id: 'market-002',
    location: 'Oakland, CA',
    averagePrice: 785000,
    medianPrice: 725000,
    priceChange: 12000,
    priceChangePercent: 1.6,
    daysOnMarket: 28,
    inventoryLevel: 'medium',
    marketTrend: 'balanced',
    recentSales: 203,
    newListings: 187,
    period: 'Last 30 Days',
  },
  {
    id: 'market-003',
    location: 'Berkeley, CA',
    averagePrice: 925000,
    medianPrice: 850000,
    priceChange: -8000,
    priceChangePercent: -0.9,
    daysOnMarket: 35,
    inventoryLevel: 'medium',
    marketTrend: 'buyers',
    recentSales: 87,
    newListings: 102,
    period: 'Last 30 Days',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    type: 'new-listing',
    title: 'New Listing Matches Your Search',
    message: '3 new properties match your "Family Homes in SF" search',
    timestamp: '2025-02-04T08:00:00Z',
    read: false,
    actionUrl: '/buyer/search?saved=search-1',
  },
  {
    id: 'notif-002',
    type: 'tour-reminder',
    title: 'Tour Tomorrow',
    message: 'Reminder: Tour at 456 Oak Street tomorrow at 2:00 PM',
    timestamp: '2025-02-04T09:00:00Z',
    read: false,
    propertyId: 'prop-001',
    actionUrl: '/buyer/tours',
  },
  {
    id: 'notif-003',
    type: 'price-drop',
    title: 'Price Reduction',
    message: 'A property in your wishlist has reduced its price by $15,000',
    timestamp: '2025-02-03T16:30:00Z',
    read: true,
    propertyId: 'prop-002',
  },
  {
    id: 'notif-004',
    type: 'message',
    title: 'New Message from Agent',
    message: 'Jennifer Martinez sent you a message about 456 Oak Street',
    timestamp: '2025-02-04T10:30:00Z',
    read: false,
    actionUrl: '/buyer/messages',
  },
];

export const mockBuyerActivity: BuyerActivity[] = [
  { date: '2025-01-28', propertiesViewed: 8, toursScheduled: 1, offersSubmitted: 1, messagesReceived: 3 },
  { date: '2025-01-29', propertiesViewed: 5, toursScheduled: 0, offersSubmitted: 0, messagesReceived: 1 },
  { date: '2025-01-30', propertiesViewed: 12, toursScheduled: 2, offersSubmitted: 0, messagesReceived: 2 },
  { date: '2025-01-31', propertiesViewed: 6, toursScheduled: 0, offersSubmitted: 0, messagesReceived: 4 },
  { date: '2025-02-01', propertiesViewed: 9, toursScheduled: 1, offersSubmitted: 0, messagesReceived: 2 },
  { date: '2025-02-02', propertiesViewed: 4, toursScheduled: 0, offersSubmitted: 0, messagesReceived: 1 },
  { date: '2025-02-03', propertiesViewed: 7, toursScheduled: 0, offersSubmitted: 0, messagesReceived: 3 },
];