worker_processes auto;

events {
  worker_connections 1024;
}

http {
  server_tokens off;

  resolver 127.0.0.11 ipv6=off;

  limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
  limit_req_status 429;

  include /etc/nginx/conf.d/https.conf;

  server {
    listen 80 default_server;
    return 301 https://$host$request_uri;
  }
}
