import jsPDF from 'jspdf';

interface EmailAttachment {
  filename: string;
  content: string; // base64 encoded PDF
  contentType: string;
}

interface EmailData {
  to: string;
  subject: string;
  body: string;
  attachments: EmailAttachment[];
}

export class EmailService {
  /**
   * Convert jsPDF document to base64 string for email attachment
   */
  static pdfToBase64(pdf: jsPDF): string {
    return pdf.output('datauristring').split(',')[1];
  }

  /**
   * Send email with PDF attachment
   * This is a client-side implementation that opens the user's default email client
   */
  static async sendEmail(data: EmailData): Promise<void> {
    // For production, this should call a backend API endpoint
    // For now, we'll use mailto: protocol with attachment simulation
    
    const { to, subject, body } = data;
    
    // Create mailto link
    const mailtoLink = `mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    
    // Open email client
    window.location.href = mailtoLink;
    
    // Note: mailto: protocol doesn't support attachments
    // In production, this should be replaced with a backend email service
  }

  /**
   * Send Schedule E via email
   */
  static async sendScheduleE(
    pdf: jsPDF,
    recipientEmail: string,
    taxYear: number,
    landlordName: string
  ): Promise<void> {
    const subject = `Schedule E - Tax Year ${taxYear}`;
    const body = `Dear Tax Professional,

Please find attached the Schedule E (Supplemental Income and Loss) for ${landlordName} for tax year ${taxYear}.

This document includes:
- Property-by-property income and expense breakdown
- All IRS Schedule E expense categories (Lines 5-19)
- Depreciation calculations
- Net rental income summary

Please review and let me know if you need any additional information.

Best regards,
${landlordName}

---
This document was generated by the Real Estate Management Platform.
For informational purposes only. Please consult with a tax professional before filing.`;

    const attachment: EmailAttachment = {
      filename: `schedule-e-${taxYear}.pdf`,
      content: this.pdfToBase64(pdf),
      contentType: 'application/pdf'
    };

    await this.sendEmail({
      to: recipientEmail,
      subject,
      body,
      attachments: [attachment]
    });
  }

  /**
   * Send Form 1099 via email
   */
  static async sendForm1099(
    pdf: jsPDF,
    recipientEmail: string,
    formType: string,
    taxYear: number,
    recipientName: string,
    amount: number
  ): Promise<void> {
    const subject = `Form ${formType} - Tax Year ${taxYear}`;
    const body = `Dear ${recipientName},

Please find attached your Form ${formType} for tax year ${taxYear}.

Payment Amount: $${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}

This is important tax information and is being furnished to the IRS. If you are required to file a return, a negligence penalty or other sanction may be imposed on you if this income is taxable and the IRS determines that it has not been reported.

Please keep this form for your tax records and provide it to your tax preparer.

If you have any questions, please don't hesitate to contact me.

Best regards

---
This document was generated by the Real Estate Management Platform.
For informational purposes only. Please consult with a tax professional before filing.`;

    const attachment: EmailAttachment = {
      filename: `form-${formType}-${taxYear}.pdf`,
      content: this.pdfToBase64(pdf),
      contentType: 'application/pdf'
    };

    await this.sendEmail({
      to: recipientEmail,
      subject,
      body,
      attachments: [attachment]
    });
  }

  /**
   * Send Tax Summary Report via email
   */
  static async sendTaxSummary(
    pdf: jsPDF,
    recipientEmail: string,
    taxYear: number,
    landlordName: string
  ): Promise<void> {
    const subject = `Tax Summary Report - ${taxYear}`;
    const body = `Dear Tax Professional,

Please find attached the comprehensive Tax Summary Report for ${landlordName} for tax year ${taxYear}.

This report includes:
- Summary of all rental income and expenses
- Property-by-property breakdown
- Expense categories sorted by IRS Schedule E line numbers
- Depreciation schedules
- Net rental income calculations

This report is designed to provide you with all the information needed to prepare the tax return efficiently.

Please review and let me know if you need any clarification or additional documentation.

Best regards,
${landlordName}

---
This document was generated by the Real Estate Management Platform.
Generated on ${new Date().toLocaleDateString()}`;

    const attachment: EmailAttachment = {
      filename: `tax-summary-${taxYear}.pdf`,
      content: this.pdfToBase64(pdf),
      contentType: 'application/pdf'
    };

    await this.sendEmail({
      to: recipientEmail,
      subject,
      body,
      attachments: [attachment]
    });
  }

  /**
   * Validate email address format
   */
  static isValidEmail(email: string): boolean {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }
}