[[contracts]]
fqn = "big_coin::BigCoin"

[[contracts]]
fqn = "roles::Roles"

[[contracts]]
fqn = "escrow::Escrow"

[[contracts]]
fqn = "treasury::Treasury"

[[contracts]]
fqn = "nft::NFT"

[[contracts]]
fqn = "lease::Lease"

[[contracts]]
fqn = "staking::Staking"

[[contracts]]
fqn = "ico::ICO"

[[contracts]]
fqn = "vesting::Vesting"

[[contracts]]
fqn = "investor_registry::InvestoryRegistry"

[[contracts]]
fqn = "compliance_policy::CompliancePolicy"
