[[contracts]]
fqn = "tailor_coin::TailorCoin"

[[contracts]]
fqn = "roles::Roles"

[[contracts]]
fqn = "escrow::Escrow"

[[contracts]]
fqn = "treasury::Treasury"

[[contracts]]
fqn = "nft::NFT"

[[contracts]]
fqn = "lease::Lease"

[[contracts]]
fqn = "staking::Staking"

[[contracts]]
fqn = "ico::ICO"

[[contracts]]
fqn = "mocks::styks_price_feed::StyksPriceFeed"
